### ISSUE TITLE
Cannot go to next round

### ISSUE THREAD

**Issue by sldafa** [Lattyware/massivedecks#103]
When everyone have chosen their cards, no signal at Judge's screen.

Hand size: 5
Comedy writer: on
White cards: 30
Automatically Mark Players As Away: on
Playing TL: 30
Revealing TL: 120
Judging TL: 30

**Comment by Lattyware** [comment]
Sounds like a bug. To be clear: was this that the game didn't advance once everyone had submitted a play, or after the czar picked a winner?

Also, did you try refreshing the page? If it worked after a refresh that would indicate an eventing error.

**Comment by Curisundere** [comment]
Same issues here.

### Precondition
We've started a game on https://md.rereadgames.com/ at room ``8V`` with a small deck. After some rounds (30-ish) the game froze with warning pop up with red warning wrote cards had been used out.
Any attempt to rejoin the game would only throw an error:
```
The server gave a response we didn’t expect.

Context for developers:
	Version: 935c60e125441f30ea7dc16f7ed7876813a0998d-dev
	Page: https://md.rereadgames.com/#8V
	English Error: The server gave a response we didn’t expect.
	Details: 500
```
With ```/api/games/8V``` responding ```500```:
```
{"error":"OutOfCards"}
```

### Buggy behaviour
Then we've tried to start several games. After all player submit their cards on 1st round, the game always froze and can not proceed to next round.

**Comment by Lattyware** [comment]
I believe I've fixed the underlying bug with the latest version, but there is a chance it is something else—the fact it showed up after you ran out of cards in a game is an interesting caveat. If you encounter the same problem again, please re-open the issue (or open a new one if you can't).
