### ISSUE TITLE
double pick in every hands

### ISSUE THREAD

**Issue by stepauli** [Lattyware/massivedecks#105]
Hi guys, I love massive decks so much and the new update is great, I am addicted to cah and I'm working on some decks of mine in italian and maybe I will translate something in english. Anyway, a few minutes ago I was testing a deck of mine and something strange happened: at every hand, black cards has double pick even if the pick is only one. 

regards

**Comment by Lattyware** [comment]
Ah, this is the result of a botched change to fix an issue where the first slot wasn't being capitalised. Fix incoming.

**Comment by Lattyware** [comment]
OK, should be fixed. I pushed out the last change a little fast to fix another issue, and forgot I hadn't tested that change. Thanks for the bug report, and I'm glad you are enjoying MD.

**Comment by stepauli** [comment]
great, now it's ok!
