### ISSUE TITLE
Ability to add multiple default decks.

### ISSUE THREAD

**Issue by CookieCoder15** [Lattyware/massivedecks#120]
Bit of a niche feature but I am privately hosting an instance of massive decks with some changes and we have a nice list of decks we all want as default but my many attempts to get multiple decks added automatically failed as I don't understand Elm at all.

It would be cool if I was able to put a list of codes somewhere in config and they would automatically be added to all new games.

**Comment by Lattyware** [comment]
Just to note up front: if you are hosting an instance of Massive Decks, [the licence (AGPL-3)](https://github.com/Lattyware/massivedecks/blob/master/LICENSE) does require you to distribute your changes as the AGPL treats network use as equivalent to distribution of a binary.

Of course, this doesn't apply to configuration, and I see the value in this kind of feature, although it is a bit of a niche use-case, a few people want to use MD like this.

It would be a nice feature to have, but probably not something I'm going to be able to jump on at the moment. If someone wanted to implement this, I would of course accept pull requests.

**Comment by CookieCoder15** [comment]
Apologies about my changes not being public, I have made a fork and I will be moving my changes across to that.

In terms of the feature request, I fully understand that this is not a priority. I will have another try at it myself when I get some free time.

**Comment by Lattyware** [comment]
No need to apologise (it is very easy to just assume no one is going to care about the changes you are making, I know from experience), and glad to hear: it really helps to get upstream contributions back where possible. If you do get a chance, I'll look forward to the pull request.

**Comment by Lattyware** [comment]
This is now implemented. You can change the default configuration in [`config.json5`](https://github.com/Lattyware/massivedecks/blob/master/server/config.json5#L78), including specifying multiple decks.

**Comment by CookieCoder15** [comment]
My config.json5 file looks like this with the lines uncommented but the decks are still not being applied by default?
```
decks: [
   {
      source: "BuiltIn",
      id: "cah-base-en",
   },
],
```

**Comment by Lattyware** [comment]
Confirmed, there is a bug that means this doesn't actually work. Should be an easy fix.

**Comment by CookieCoder15** [comment]
Is it possible for you to add comments in the config on how to add decks from different sources as default? I am not sure what the IDs are for JSON Against Humanity.

**Comment by Lattyware** [comment]
That should fix the issue where the default wasn't being honoured, and I also added examples of other sources.

For JSON Against Humanity, the IDs are based on the keys in the JSON. Probably the easiest way to find them (rather than scouring through the huge amount of JSON) is to look at the directory names [in the repo](https://github.com/crhallberg/json-against-humanity/tree/v2/src).
