### ISSUE TITLE
Automatically switch players over to next round after a few seconds

### ISSUE THREAD

**Issue by donicrosby** [Lattyware/massivedecks#121]
After a round is complete, all players and the czar after a few seconds (~3-5) be shown the new round. It is a little confusing for new users coming from other online CAH platforms that they need to either click or wait for 30 seconds. Maybe this should be configurable so that if users want to screenshot the round on their device without having to go into the history.

**Comment by Lattyware** [comment]
This is actually how MD1.0 used to work, but was changed as people tended to miss the result if it automatically advanced and get confused. It'd be reasonably easy to have an "auto-advance" option client-side though, to have that behaviour as an option.

**Comment by donicrosby** [comment]
Thanks for the quick reply! My friends and I have been kicking the tires of this project and this was one of the things that drove them nuts. I'll learn TS and Elm in the coming weeks so I can help out with some of the other issues you guys have.

**Comment by Lattyware** [comment]
The latest version has the "Automatically Advance Round" option in the settings. Hopefully that gives a good solution to this (how quickly it advances is based on the Finished Time Limit set for the game).
