### ISSUE TITLE
Blank cards get cleared when another player plays or reascends a white card

### ISSUE THREAD

**Issue by donicrosby** [Lattyware/massivedecks#122]
When a player is writing a blank card what ever is being typed into it gets deleted when another player plays a card.

**Comment by Lattyware** [comment]
I took a quick look at this and I can't reproduce it just testing whenever someone plays a card in a simple test setup, but I have seen this myself intermittently when playing with people. I'm not quite sure what is causing it, but it definitely is a pain.

**Comment by donicrosby** [comment]
Does Elm re-render the objects when it notices some change from the backend? If that's the case I'm wondering if whatever object that's holding the blank card's text isn't being persisted through that update from the server.

**Comment by Lattyware** [comment]
Elm doesn't have any individual pieces of state, the whole view is rendered off the singular model, so it must be that the model is being updated and the value cleared for some reason. The thing is, we don't do that anywhere except initialisation.My thought is it must be an issue with losing the connection to the server temporarily and reconnecting in the background, which would explain why I'm not seeing it testing locally.

Of course, the ideal solution would just be to store the state remotely, but that would require something a bit smarter than just updating the server on every keystroke. Probably something like every time the user clicks off a card or submits their play.

**Comment by donicrosby** [comment]
Maybe use the local storage in the client's browser to store the state of the card? That way when the client "reconnects" it's still stored locally and you don't have to deal with sending keystrokes to the server? Maybe set it so the card text "expires" either after the length of the current round or the round ends.

**Comment by Lattyware** [comment]
We use local storage for settings and stuff at the moment, so it definitely is an option. The main issue with doing that is managing the life-cycle—we'd have to make it per-game (as people could play two games at once, etc...), and as we can't guarantee players will leave the game in a way we can work with (most just close a tab), we'd have to have some background garbage collection going on in the game to ensure we don't leave stuff floating around in local storage for no reason.

So both options have some annoying implementation cost. The main reason I erred towards the side of server state is that we already have to do that at some point (when the player submits the play, it obviously has to go server-side), so some of that infrastructure is in place. It also technically would mean you could swap devices without losing your plays, although I think that's a really niche use case. Honestly, it is a bit of a toss-up.

**Comment by Lattyware** [comment]
OK, I put together an implementation of the server-side solution, and I think it seems to work pretty well. Please open a new issue if you run into any problems with it.
