### ISSUE TITLE
Untranslated strings.

### ISSUE THREAD

**Issue by Lattyware** [Lattyware/massivedecks#123]
Some new strings have been introduced, resulting in some holes in the translation:

- AutoAdvanceSetting
- AutoAdvanceExplanation

They look like this at the moment:

```
        -- TODO: Translate
        AutoAdvanceSetting ->
            [ Text "Automatically Advance Round" ]

        -- TODO: Translate
        AutoAdvanceExplanation ->
            [ Text "When a round ends, automatically advance to the next one rather than waiting." ]
```

Obviously, no pressure or obligation, but I'll just mention @Fittl3 and @marcoburato here in case they can help out given they made the original translations. Obviously open to anyone else contributing as well though.

**Comment by Lattyware** [comment]
On a side note, I'm interested if anyone has good ideas for process on this kind of thing. I'm not sure what a good way of introducing new strings would be, seems a little clunky to open a new issue like this every time.

**Comment by marcoburato** [comment]
No probs, I've updated the translation with #124 

I don't have much experience with managing software localisation, but I know there are websites where everyone can see the status by language and contribute.
LibreOffice for instance has this, which is based on [Weblate](https://weblate.org):
https://translations.documentfoundation.org/

I suppose the idea is to store all the strings outside git and import them periodically, or just keep the main language in the codebase and bundle the localised strings when deploying.
One challenge is that all solutions I've seen seem to revolve around the idea of just providing an alternative string depending on the language, but massivedecks also uses the Plural function and other things to dynamically combine text blocks. Plurals are a common issue and it seems that Weblate already has support to deal with those.
