### ISSUE TITLE
Translation Updates

### ISSUE THREAD

**Issue by Lattyware** [Lattyware/massivedecks#127]
Some new strings got added with the latest update.

```
    | LobbyNameLabel -- A label for a lobby name field.
    | DefaultLobbyName { owner : String } -- The string that is used for the name of a new game by default, given the owner's username.
...
    | BuiltIn -- A term referring to decks of cards that are provided by this instance of the game.
```

```
        -- TODO: Translate
        LobbyNameLabel ->
            [ Text "Game Name" ]

        -- TODO: Translate
        DefaultLobbyName { owner } ->
            [ Text owner, Text "'s Game" ]

...

        -- TODO: Translate
        BuiltIn ->
            [ Text "Built-in" ]
```

This version also adds the ability to change the recommended deck for the language.

```
, recommended = "cah-base-en" |> BuiltIn.Id |> Source.BuiltIn
```

I'd prefer not to ship with references to random user's Cardcast decks that could change under our feet, and Cardcast only had the pinned "official" CAH base deck in English, as far as I can see. As you can see, we now ship a built-in version of the English deck.

Obviously localizing the base deck itself is a big task, and something that has already been done around the web. CaH used to have some sanctioned translations, but I don't see them any more. 
I'd be interested to know if there were known good versions, etc... Some googling lead to [an Italian version](https://s3.amazonaws.com/cah/CAH_ItalianByFederico.pdf).

**Comment by Fittl3** [comment]
I've found [this version](http://s3.amazonaws.com/cah/CAH_PortugueseByMarcelo.pdf), that is used in a [mod for Tabletop Simulator](https://steamcommunity.com/sharedfiles/filedetails/?id=403373511), and it seems to have a good rating.

**Comment by Lattyware** [comment]
Like the Italian version I linked, that appears to be stored on the Cards Against Humanity S3 bucket, so while they appear to have stopped endorsing localizations, presumably they did share it at some point, which seems like as strong as "official" as we are likely to get, so yeah, sounds like a decent option.
