### ISSUE TITLE
Add a win condition (score limit).

### ISSUE THREAD

**Issue by Lattyware** [Lattyware/massivedecks#13]

**Comment by Avamander** [comment]
Also ignoring the bot when this feature is implemented would be nice.

**Comment by Lattyware** [comment]
I can imagine people wanting to lose to bots for comedic effect ("we are all so bad we lost to random cards", as the CaH rules suggest, "all players go home in a state of everlasting shame"), so we'd probably want to make it an option on the house rule. I can see the value in not being able to lose to bots though.

**Comment by Lattyware** [comment]
Added in 2.x.
