### ISSUE TITLE
Remove single Card from Hand

### ISSUE THREAD

**Issue by huemmerj** [Lattyware/massivedecks#131]
I know that there is a possibility to get a completely new hand. Is it possible to remove individual cards from my hand? When a card is removed i want to get a new one in the next round.

thanks in advance

**Comment by Lattyware** [comment]
Would #47 work for your case?

**Comment by huemmerj** [comment]
Yes. Thank you. This would be a really nice rule.

**Comment by Lattyware** [comment]
Sure, I'll close this as a duplicate then, and that issue will be the one to watch, feel free to comment there if you have anything more to add, or open a new issue for anything else.
