### ISSUE TITLE
Not advancing to Judging using Postgres.

### ISSUE THREAD

**Issue by AjayACST** [Lattyware/massivedecks#132]
I used the config.json5 and docker-compose.yml file in postgres and the game works I can access it and select cards but once everyone has added their cards the person who is judging won't be able to select the cards.

**Comment by AjayACST** [comment]
This just seems to be an issue with the postgres example deployment because I have now deployed it with the memory example deployment and is now working.

**Comment by Lattyware** [comment]
Ah, sounds like there is a bug with the postgres back-end. It doesn't see as much testing—I should probably switch the hosted instance to it to get more testing on it at some point.

Thanks for reporting this, when I get a chance I'll take a look at fixing it (although pull requests are, as always, welcome).
