### ISSUE TITLE
Setting never have I ever on by default in config

### ISSUE THREAD

**Issue by clidx** [Lattyware/massivedecks#142]
Is this possible, it's not documented in config.json5.

I've been messing around with this for the last few days and it's a brilliant program, thanks for your efforts.

**Comment by Lattyware** [comment]
Ah, yeah, that just didn't get added to the example config. As with packing heat, it doesn't have any sub-options so just giving an empty object under the name should enable it by default, i.e:

```
houseRules: {
  ...
  neverHaveIEver: {}
}
```
