### ISSUE TITLE
Searching for public games causes a 500 error

### ISSUE THREAD

**Issue by dantherussell** [Lattyware/massivedecks#150]
I was trying to search for public games when I got the following error:

The server gave a response we didn’t expect.

Context for developers:
	Version: f7841f99945073c97a2163624cbbadee5a6816ce-dev
	Page: https://md.rereadgames.com/#find
	English Error: The server gave a response we didn’t expect.
	Details: 500

**Comment by Lattyware** [comment]
Fixed, there was a sneaky `any` in some TypeScript types used in the game that allowed a bug to sneak through, I can't reproduce this any more so seems fixed.
