### ISSUE TITLE
Rejoin after exiting

### ISSUE THREAD

**Issue by clidx** [Lattyware/massivedecks#158]
If someone closes the browser window or hits back by accident (more likely on a smartphone than desktop/laptop) then they are out of the game completely. They can't rejoin with the same username. It would be nice if the server lets the username be reused with the same score with the approval of the host.

But I have to admit, I'm the one who keeps doing this and I'm the admin since I host my own instance... not sure how you'd get around that! Maybe all the other players could reapprove the host? Or maybe setting a cookie for the game is the best way?

Please help me work around my 10 thumbs.

**Comment by Lattyware** [comment]
So if you close the window, you should be able to rejoin the game—if you go to the Join tab there should be a Rejoin link given if the game is still running, clicking that should get you back into the game. If you hit back, hitting forward should also work.

![image](https://user-images.githubusercontent.com/1239492/88330864-f703eb00-cd23-11ea-810c-0f41140c90ba.png)

If you explicitly leave the game, you can't rejoin currently (see #46), but it is pretty hard to do that by mistake, and shouldn't happen if you just do what you have described.

If you are finding you can't go back to the game like this, then something is wrong. The game uses the local storage API in your browser to store data about what games you are in. You would have to be using a *really* old browser for this not to be supported, but maybe an extension you use is blocking it or clearing the data?

**Comment by clidx** [comment]
I haven't noticed a rejoin option but maybe I've just missed it. Don't know
when I'll be playing again so I'll close this for now and reopen it if
necessary.

**Comment by Lattyware** [comment]
Sure, or if you want there is no harm in making a new game just to test it.

Even if it was just you missing the option, this might be a sign we want to change the way it is presented so it is more obvious.

**Comment by clidx** [comment]
The option is indeed there and clear. If I notice it missing another time
I'll get back to you
