### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by karenvanpeteghem** [Lattyware/massivedecks#163]
I was [replace with a short explanation of what you were doing] when I got the following error:

The server gave a response we didn’t expect.

Context for developers:
	Version: 219a5b2baa211962be04e4066993277dcb62261b-dev
	Page: https://md.rereadgames.com/#new
	English Error: The server gave a response we didn’t expect.
	Details: 526

**Comment by Lattyware** [comment]
Sorry about this, this was a simple administration error where the server wasn't restarted correctly when a new SSL certificate was issued. It is now working again.
