### ISSUE TITLE
Polish translation problems

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#165]
Hello! I just started making a Polish translation of your game and I encountered some problems with it, because of the complexity of my language. I wanted to ask how should I deal with them:

# Plural forms
You can't really make a generic plural form function for this language—there are a lot of plural endings, and they're often irregular. I see that e.g. German has some exceptions there, I might try doing something this way.

## Paucal
I believe that's what it's called. Our words don't have just singular and plural. The endings change depending on the last digit of the number (and some other things), e.g.  
1 pies, 2 psy, 3 psy, 4 psy, 5 psów, etc.

# Grammatical cases
In Polish, nouns change their suffixes depending on their function in a sentence (if it's the object, it'll be different than if it were a subject, for example), but the translation sometimes requires “putting” a string inside another string. In most cases, it's understandable, but not really natural. Of course changing suffixes of nicknames doesn't really matter (no one does that in translation), but with the words like “card“ or “deck”, it'd be great.

# Gender
Every noun in Polish has its gender—either male, female, or neuter, and you sometimes have to change specific words next to the noun so it sounds natural. I can see that Portuguese has something like that in their plural translation, I'd like to replicate that.

The point is that I don't really know how this language system works exactly, nor I know the syntax of this Elm language (I know some other languages, though), so it'd be incredible if you could help with it!

**Comment by Lattyware** [comment]
First of all, thanks for wanting to contribute!

In general, you can copy what German is doing for plurals as you say. For the other options, it basically comes down to two routes:

- If the rules are consistent in a way they can be automated, then let me know the rules and I can write a function to do the appropriate things for the case.
- If the rules are not consistent, then you will need to (as with the plural case) just handle the possible cases manually. If this requires some more information (as in the Portuguese translation with the gender) then let me know and I can add that in as well.

In general, feel free to just try and translate, and if you run into places you have a special case, add a placeholder and make a note of the issue. You can let me know what special cases you need to deal with and I can write up additional helpers as needed. The ideal situation is to give me some examples of the cases you need the thing and any general rules if there are any.

Let me know if that makes sense, or if I need to clarify anything. If in doubt, just ask, and feel free to put up partial work in a pull request so you can point to specific lines and stuff if that is useful.

**Comment by TheChilliPL** [comment]
I translated most of the simple things [here](/thechillipl/massivedecks). Tomorrow I'll try to deal with all this stuff (right now cases are incorrect etc.) and I'll let you know if I'm stuck with something,

**Comment by Lattyware** [comment]
As of the latest commit I've fixed changed the way that plurals work, which should make it easier to implement and to know that you have all the required translations done.

**Comment by TheChilliPL** [comment]
Thanks, I'll try to convert the old translation code to the new plurals system and then deal with the grammar and all

**Comment by TheChilliPL** [comment]
So there's a small problem:
I managed to do most of the declension stuff, but I don't know if I can integrate it into the Noun type, as there's only the noun parameter and the quantity parameter, and the text it should display depends also on the grammatical case.
For example, the declension table for the black card looks like
```elm
declTable noun =
    case noun of
        Call ->
            fromList [
                "czarna karta",
                "czarnej karty",
                "czarnej karcie",
                "czarną kartę",
                "czarną kartą",
                "czarnej karcie",
                "czarna karto",
                "czarne karty",
                "czarnych kart",
                "czarnym kartom",
                "czarne karty",
                "czarnymi kartami",
                "czarnych kartach",
                "czarne karty"
            ]
...
```
The 1st seven are the 7 singular cases, the rest are plural, except that in some cases the noun gets locked to the 3rd case depending on the exact plural number (the details aren't that important)
Then, I'm using this function to get the desired string:
```elm
{-| Declines the specified noun to the specified case and quantity.
-}
decl : Noun -> Quantity -> DeclensionCase -> String
decl noun quantity declCase =
    let
        realCase = paucal declCase quantity
        realCaseIndex = caseIndex realCase + case quantity of
            1 -> 0
            _ -> 7
    in
        get realCaseIndex (declTable noun)
        |> Maybe.withDefault ""
```
The problem with this is that the output is a string and not a Noun, so it will only be displayed as raw text, without any tooltips etc..
Any idea what to do with it?
You can see the whole code [here](https://github.com/TheChilliPL/massivedecks/blob/Lettyware-master/client/src/elm/MassiveDecks/Strings/Languages/Pl.elm). It gives a lot of errors in my IDE cause it still attempts to use the old plural function, but ignore it, I'll be fixing that once my declension works.

**Comment by Lattyware** [comment]
Sure, I can see what you are going for here. I appreciate the effort, it's a complex one.

I can help write some more custom code specific to the translation to make this a bit easier. Am I right in saying that what you really need here is the ability to pass some language-specific custom context through `Ref`? I think that would solve your problem, and should be possible.

For clarity, the change would mean that your translate function becomes:

    translate : Maybe DeclensionCase -> MdString -> List (Translation.Result DeclensionCase)

And then each time you use `Ref` or `Raw` you provide it the `DeclensionCase`, which you then get back in `translate` when it translates that section.

Does that match up with what you were looking for?

**Comment by Lattyware** [comment]
Also, if I am understanding what you want to achieve correctly, you could have a slightly easier to work with structure by doing something like this:

```
type DeclensionCase
    = Nominative -- Mianownik   kto co
    | Genitive -- Dopełniacz  kogo czego
    | Dative -- Celownik    komu czemu
    | Accusative -- Biernik     kogo co
    | Instrumental -- Narzędnik   z kim z czym
    | Locative -- Miejscownik o kim o czym
    | Vocative -- Wołacz


type alias DeclensionCaseValue =
    { singular : String
    , plural : String
    }


type alias DeclensionCases =
    { nominative : DeclensionCaseValue
    , genitive : DeclensionCaseValue
    , dative : DeclensionCaseValue
    , accusative : DeclensionCaseValue
    , instrumental : DeclensionCaseValue
    , locative : DeclensionCaseValue
    , vocative : DeclensionCaseValue
    }


select : DeclensionCase -> Quantity -> DeclensionCases -> String
select declCase quantity =
    selectCase declCase >> selectValue quantity


selectCase : DeclensionCase -> DeclensionCases -> DeclensionCaseValue
selectCase declCase =
    case declCase of
        Nominative ->
            .nominative

        Genitive ->
            .genitive

        Dative ->
            .dative

        Accusative ->
            .accusative

        Instrumental ->
            .instrumental

        Locative ->
            .locative

        Vocative ->
            .vocative


selectValue : Quantity -> DeclensionCaseValue -> String
selectValue quantity =
    case quantity of
        Quantity 1 ->
            .singular

        _ ->
            .plural


declTable : Noun -> DeclensionCases
declTable noun =
    case noun of
        Call ->
            DeclensionCases
                (DeclensionCaseValue "czarna karta" "czarne karty")
                (DeclensionCaseValue "czarnej karty" "czarnych kart")
                ...

        ...

```

**Comment by TheChilliPL** [comment]
I actually think the arrays will work well here. The main point is that I can't really do it inside the Noun thing that adds the formatting, cause I need more information about current context, and Noun only gets the amount, and the Noun to translate. I could just submit it as raw string, but it doesn't preserve the formatting

**Comment by Lattyware** [comment]
> I actually think the arrays will work well here. The main point is that I can't really do it inside the Noun thing that adds the formatting, cause I need more information about current context, and Noun only gets the amount, and the Noun to translate. I could just submit it as raw string, but it doesn't preserve the formatting

Sorry, I may have distracted a little with that comment, let's ignore that for now and focus on the more important part.

Would the solution mentioned in [this comment](https://github.com/Lattyware/massivedecks/issues/165#issuecomment-702224465) work to resolve that problem? You get the context information (whatever that is, I've used DeclensionCase, but you could pass any data you wanted) in `translate`, and pass it in whenever you use `Ref` or `Raw`.

**Comment by TheChilliPL** [comment]
I think it might work, but wouldn't that mean adding this type to every other language too? Different languages might need different parameters to work

**Comment by Lattyware** [comment]
> I think it might work, but wouldn't that mean adding this type to every other language too? Different languages might need different parameters to work

I can set it up so that it is internal to the language, so each language can have their own custom context as necessary, and languages that don't need a language-specific context can use `Never`. I'll throw together the changes.

**Comment by TheChilliPL** [comment]
It's great if it's possible, it would surely help with that

**Comment by Lattyware** [comment]
OK, I haven't gone over it carefully but it runs and looks fine, so while I don't want to push it into master quite yet, there are the changes in a PR (#173) so you can see if those changes work for you, feel free to rebase onto them and try it out or whatever is the best workflow for you if it looks right, or let me know if it doesn't quite work.

**Comment by TheChilliPL** [comment]
What exactly does it mean:
```elm
translate : Maybe never -> MdString -> List (Translation.Result never)
```
is `never` a type? Can't really open the IDE now and find where it's declared

**Comment by Lattyware** [comment]
So in the other translations that never actually has a value, so we just use `never` as a placeholder.

As you want to use the context, you'll want something like:

    translate : Maybe DeclensionCase -> MdString -> List (Translation.Result DeclensionCase)

(Basically, that `never` can become whatever type you want, it is just never where we never use the value).

**Comment by TheChilliPL** [comment]
Yeah, it should definitely work then! I'll try doing that declension tomorrow. Thanks for the help!

**Comment by Lattyware** [comment]
No problem, thanks for the work on the localization!

**Comment by TheChilliPL** [comment]
I've just done most of the translation. Some small things are left untranslated or unsure.
What's the easiest way I could try out this translation in-game before sending a PR? (to be sure everything is right)

**Comment by Lattyware** [comment]
You should be able to run the game [as per the wiki](https://github.com/Lattyware/massivedecks/wiki/Setting-Up-A-Development-Environment#getting-running):

> You can then run `npm run dev` in the `server` directory, and likewise `npm run dev` in the client directory. This will start the two components in development mode. You can now make changes to the source in your favourite editor and they will automatically react to changes. By default, you can visit `http://localhost:8080/` to see the game running.

**Comment by TheChilliPL** [comment]
I managed to start the server by using
```
npm install
npm run dev
```
and it started the server at port 8081, but trying to open it in browser returns plain text:
```
Cannot GET /
```

**Comment by TheChilliPL** [comment]
I can't get the client to start. I've tried installing webpack several times, it is in the global node_modules directory, but node just doesn't see it
![image](https://user-images.githubusercontent.com/18823939/94901584-2444e600-0497-11eb-9c6e-7c1fff00e21a.png)

**Comment by TheChilliPL** [comment]
Uhh, right now it throws a different one:
```
> npx webpack-dev-server --mode=development

internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'json-parse-better-errors'
```

**Comment by TheChilliPL** [comment]
Uhh, I think I managed to fix that

**Comment by TheChilliPL** [comment]
![image](https://user-images.githubusercontent.com/18823939/94903068-81da3200-0499-11eb-8b7c-28cbab145b1e.png)
Declension works! Thanks a lot for all the help, I'll look for some mistakes (already found two—invalid declension case and a missing space) and when it's all done, I'll send a pull request

**Comment by Lattyware** [comment]
Hey, glad you managed to get it all working, I'll take a look at that PR and merge it through ASAP! Thanks for all the work getting this one done!

I'll close this issue in favour of the PR for any further discussion if needed, but obviously feel free to open new issues for anything else.
