### ISSUE TITLE
Capitalize the first word in a black card

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#167]
If the black card starts with a space for a white card and it gets filled, it should get capitalized like on the white cards alone.

**Comment by Lattyware** [comment]
This depends on the deck in use. Decks specify what slots should be capitalised (or other things like being made ALL CAPS), so the deck should do so where it makes sense to.

 - If the black card in question was in a built-in deck, than that'd be a bug. 
 - If it is with a deck from JSON Against Humanity then we use some heuristics to determine if the slot should be capitalised, one of those is that it begins the card, so that would be a bug there if it didn't.
 - If it is in a deck from Many Decks, it is down to the deck author to chose that. It'd probably make sense to make the editor do it by default, but ideally we'd like not to force it as there are some cases where you'd like an intentionally badly formatted thing for comedic effect, etc...

**Comment by TheChilliPL** [comment]
How to do that in a Many Decks deck?

**Comment by Lattyware** [comment]
If you click on a black card in the list of cards to edit it, it will show up:

![image](https://user-images.githubusercontent.com/1239492/93026863-08b98e80-f601-11ea-9c1c-cf9861004440.png)

If you then click the slot it will be highlighted (as shown) and you can then press the buttons up top to change the transform that will be applied to the slot. The first is capitalisation, the second is all caps.

**Comment by TheChilliPL** [comment]
Thanks, it works! I think there should be some easy way to see the capitalization in the editing screen—e.g. a semi-transparent text `abc` in the slot

**Comment by Lattyware** [comment]
Agreed, there is an existing task Lattyware/manydecks#12 for improving the call editor that should include that. I've never really been happy with it (the whole of Many Decks was made very quickly in response to Cardcast dying, there are a lot of papercuts still I'd like to fix when I find the time).

**Comment by TheChilliPL** [comment]
Good to hear. Also, I think importing is broken. Couldn't get it to work—the import button was disabled and even canceling was broken as after that, the toggle switch about deleting the deck appears like 20 times.

P.S. Thanks for the Massive Decks anyway—I wanted to play it with friends today and it (Cardcast) was dead so I searched for an alternative, I found your project and despite a few bugs, it's great!

**Comment by Lattyware** [comment]
Hrm. A quick test and importing appears to work fine for me. Not sure what happened there, but if you can reproduce it consistently, let me know your browser version and platform (windows, mac, linux, etc...) and I'll try and work out what is going on there.

And no problem, glad it works for you and your friends.

**Comment by TheChilliPL** [comment]
I mean the importing with a textbox. Importing a whole deck from a file does work.
![image](https://user-images.githubusercontent.com/18823939/93027418-f0e80780-f60c-11ea-8893-268d0c9f3ac7.png)
The *Submit* button is grayed out, and after clicking on *Cancel*:
![image](https://user-images.githubusercontent.com/18823939/93027427-03fad780-f60d-11ea-91c1-c048dd4df539.png)

**Comment by Lattyware** [comment]
Hrm, I can't reproduce that. As soon as something is typed the import button should stop being greyed out.

The icon bottom right in the text field looks like it belongs to a browser plugin? There is a chance that plugin is breaking the page.

Elm uses a diffing mechanism which can break if the page is changed by something else, and when it breaks you can see things like the duplication of the deletion elements there, which you wouldn't really see any other way, so I suspect that might be what is going on.

If I am right about it being a plugin/extension, could you try with the extension disabled, and if that fixes it, let me know what the extension is so I can try to work out how to mitigate the bug it is causing?

**Comment by TheChilliPL** [comment]
![image](https://user-images.githubusercontent.com/18823939/93029011-51307680-f618-11ea-87e5-36eada25f2ba.png)
I have some problems—can't sign in with Google using incognito mode. After going through Google log in Window, nothing happens and the sign in with Google button stops working. Console is also empty

**Comment by Lattyware** [comment]
The Google thing is a known issue with sign in with google in general in that it fails to work if the user blocks 3rd party cookies (which Firefox does by default in Incognito mode, I believe—and is generally a good idea anyway). Cardcast actually had this same issue for me.

Not much we can do about this, but we should probably add a warning so people at least know why it is failing. There is an open issue related to this at Lattyware/manydecks#16.

**Comment by TheChilliPL** [comment]
Uhh, it seems the site doesn't work on Edge at all
![image](https://user-images.githubusercontent.com/18823939/93029163-8db0a200-f619-11ea-8562-d8856fdc4a9a.png)

**Comment by TheChilliPL** [comment]
(only the background is visible)

**Comment by TheChilliPL** [comment]
The importing seems to be working properly on mobile Chrome, though

**Comment by Lattyware** [comment]
Ah, yeah. It is totally untested in Edge as I don't run a Windows environment so it is hard to test.

`vendors` is all the dependency code, so this isn't a bug in the main code-base. I'd suspect this is probably an issue of a missing browser feature or something (because Edge), so the solution may be tweaking the target for Babel.

**Comment by TheChilliPL** [comment]
Going back to the original issue:
Seems like the `Aa` button changes the string to a `Title Case`, not a `Sentence case` like it should be e.g. at the beginning of a card

**Comment by Lattyware** [comment]
Ah, yeah, don't know when that got introduced, but even at a glance I can see this mistake causing that:

In [_cards.scss](https://github.com/Lattyware/massivedecks/blob/master/client/src/scss/_cards.scss#L38):

`.capitalize:first-child` is `.capitalize` where it is the first child, what we want is `.capitalize > :first-child`—the first child *of* `.capitalize`.

Thanks for the spot.

**Comment by TheChilliPL** [comment]
You could even add title case as a separate option in the future when you update Many Decks—I could see some cases it'd be useful
