### ISSUE TITLE
Casting to TV?

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#169]
When translating game strings, I noticed casting to TV, probably using Chromecast.
Is it already implemented or is it just strings? How to turn it on? I can't find that option in the game.

**Comment by Lattyware** [comment]
It is implemented in-game. If you are using a compatible browser (Chrome) and have a device on your network that supports casting, the button should show up next to the menu button top-left.

I just tested it and it looks like there is a bug stopping this from happening:

```
cast-client.08f2d5a49bf24f6b7afa.js:1 Uncaught ReferenceError: $jscomp is not defined
    at window.__onGCastApiAvailable (cast-client.08f2d5a49bf24f6b7afa.js:1)
    at chrome.cast.fa (cast_sender.js:100)
```

I suspect this is an error from the recent change to using the closure compiler for minification, as the chromecast library is an extern that has to be handled specially.
