### ISSUE TITLE
Server keeps responding 404

### ISSUE THREAD

**Issue by mddigaetano** [Lattyware/massivedecks#171]
## Describe the bug
I deployed the application in docker (tag 2.3) behind a nginx reverse proxy.
I've tried configuring both postgres and in-memory storage.
The site runs, but when i try to create a new game it hangs where it should appear the deck and rule selection screen.
Checking the server logs, it receives the request but keeps responding with a 404 error.
This is one of such reply:
```
info: HTTP GET /api/games/ZO
{
  "meta": {
    "req": {
      "url": "/api/games/ZO",
      "headers": {
        "x-forwarded-for": "192.168.16.8",
        "host": "client:8080",
        "connection": "Upgrade",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
        "accept": "*/*",
        "accept-language": "en,it;q=0.8,it-IT;q=0.5,en-US;q=0.3",
        "accept-encoding": "gzip, deflate, br",
        "sec-websocket-version": "13",
        "origin": "https://myhost.com",
        "sec-websocket-extensions": "permessage-deflate",
        "sec-websocket-key": "4PO8Z9h4B+xpMr7vxg4DKQ==",
        "dnt": "1",
        "pragma": "no-cache",
        "cache-control": "no-cache"
      },
      "method": "GET",
      "httpVersion": "1.1",
      "originalUrl": "/api/games/ZO",
      "query": {}
    },
    "res": {
      "statusCode": 404
    },
    "responseTime": 3
  },
  "timestamp": "2020-09-20T12:26:27.018Z"
}
```
Also, the config file in the deployment folder is outdated because of the new deck sources.

## How to reproduce the bug
Steps to reproduce the behaviour:
1. Deploy the server with docker (it does not matter if with postgres or in-memory)
2. Create a new room
3. It hangs

### Expected behaviour
It should prompt the deck and rule selection screen.

**Comment by Lattyware** [comment]
Hrm. Not sure what would cause this. Could you try with the `latest` tag and see if this has been fixed in the latest version?

**Comment by BombTheDodongos** [comment]
I'm encountering this same issue with the latest tag. If I access the site via local IP/port combo it works fine, but the moment I go through my nginx proxy it 404's endlessly with the same errors as above. Looks like it's getting a 201 to the POST request on my end, too. 
![image](https://user-images.githubusercontent.com/49031517/94492998-8c56ac00-01b9-11eb-90e8-242bbf2e802f.png)

**Comment by Lattyware** [comment]
When you say it is behind a reverse proxy, do you mean the one in the client image, or another one on top? I'm assuming it must be the latter and must be some issue with the configuration there.

If so, my bet would be that this is failing because it is a websocket at the reverse proxy isn't accepting the request to upgrade to one. I'd suggest taking a look at the configuration we do in the client for nginx and copying the relevant parts in that case.

**Comment by mddigaetano** [comment]
I'm sorry, I was a bit busy this week and completely forgot about this issue.

> If so, my bet would be that this is failing because it is a websocket and the reverse proxy isn't accepting the request to upgrade to one. I'd suggest taking a look at the configuration we do in the client for nginx and copying the relevant parts in that case.

That was exactly the case, I didn't know about Upgrade header on WebSockets.

On the external reverse proxy, I had to edit the location section like this:
```
location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_pass http://client:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
```
And I can confirm it also works for the recent 2.4 version.

Thank you for your help

**Comment by Lattyware** [comment]
Not a problem at all. Glad that's solved for you.

@BombTheDodongos I'll assume this will be a fix for you too and close the issue, but if your problem turns out to be different, and isn't solved by this, feel free to open a new issue for it.
