### ISSUE TITLE
Hacktoberfest update

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#177]
Recently, Hacktoberfest updated its rules and by default, only repos with a topic of `hacktoberfest` are valid for the Hacktoberfest PR-s (see the 2nd source). Seeing the Hacktoberfest label on one of the issues, I thought it'd be great to add it to this repository, to attract more contributors.
After that, PR-s have to be merged, approved, or labeled with `hacktoberfest-accepted`.

Sources:
- https://hacktoberfest.digitalocean.com/hacktoberfest-update
- https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by Lattyware** [comment]
Thanks for pointing that out, I've done that and will tag stuff appropriately going forward for the event.
