### ISSUE TITLE
What part of the code deals with the game settings menus ?

### ISSUE THREAD

**Issue by mukberty** [Lattyware/massivedecks#181]
What part of the code deals with the game settings/rules menu (where user gets to pick hand size etc.)?
If I wish to change some of the default settings on my server , which part would I have to edit ? 
Also , which part deals with decks menu ?

Thanks a ton!

**Comment by Lattyware** [comment]
The default settings are all defined [in the server configuration](https://github.com/Lattyware/massivedecks/blob/a9a49afd2fcbe5b5515838ca9761629f810b5358/server/config.json5#L55).

The configuration for the game is done in [`Configure.elm`](https://github.com/Lattyware/massivedecks/blob/master/client/src/elm/MassiveDecks/Pages/Lobby/Configure.elm), and that's also where decks are added and removed.

**Comment by mukberty** [comment]
Thanks a lot. 
Is it possible for me to change the minimum number of players needed to start a game to 2 instead of 3 ?

**Comment by Lattyware** [comment]
Uh, you can, but I can't say the game will be very interesting like that.

You can see [the check we do to stop that in the client](https://github.com/Lattyware/massivedecks/blob/master/client/src/elm/MassiveDecks/Pages/Lobby/Configure.elm#L547).

**Comment by mukberty** [comment]
Wow. 
Last question, what do I have to edit such that instead of something like `https://md.rereadgames.com/#M57W` it will display `https://customdomain.com/#M57W`.
Lovely project and thanks a lot ;)

**Comment by Lattyware** [comment]
All the strings are defined for [their respective languages](https://github.com/Lattyware/massivedecks/tree/master/client/src/elm/MassiveDecks/Strings/Languages).

The URL is based on the host provided by the client, so it should change to the correct URL for however the user accesses the game.

[The start page](https://github.com/Lattyware/massivedecks/blob/master/client/src/elm/MassiveDecks/Pages/Start.elm) is where you want to look for the other bits.

**Comment by mukberty** [comment]
Thank You.
I understood how I can solve the 1st , 2nd and 4th questions.
To remove the "`Many Decks`" hyperlink , do I have to edit [this](https://github.com/Lattyware/massivedecks/blob/a9a49afd2fcbe5b5515838ca9761629f810b5358/client/src/elm/MassiveDecks/Pages/Start.elm#L201) part ?

**Comment by Lattyware** [comment]
Yeah. I'd suggest just trying it and seeing, it should be pretty clear what does what.
