### ISSUE TITLE
Automatic language choosing

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#184]
The default language of the game should be chosen based on the user's browser language preferences (HTTP header) or alternatively localization, so they don't have to change it manually.
It'd be nice if there was a way to link to a specific language using a query parameter (so playing with my Polish friends, I could give them a link like `https://md.rereadgames.com/#CODE?lang=pl` so they have Polish set automatically as they join

**Comment by Lattyware** [comment]
We should be doing this already, but presumably it isn't working for you?

Right now we only match to exact matches to the language code (there is an existing bug, #113 for doing fuzzier matching), so there is a chance your browser isn't giving an exact match for some reason.

Could you give the result of `navigator.languages` in your browser console?

**Comment by TheChilliPL** [comment]
Oh, I've got en-US in it for some reason
In a sec I'll ask my friends if it works for them

**Comment by TheChilliPL** [comment]
Seems it does work for them, good

**Comment by Lattyware** [comment]
I'm not sure about the query parameter. In general it doesn't really make sense to allow whoever sets the URL to set the language, as URLs are generally shared across clients that may want different languages. While it is true that mostly people will share a language in a game, that isn't guaranteed.

I think generally most people should have the language set in their browser, and where they don't selecting it manually isn't a huge issue as it should be a rare case.

**Comment by Lattyware** [comment]
I'll close this issue as I think #113 covers any changes we'd want to make to this functionality.
