### ISSUE TITLE
Time limits don't seem to work

### ISSUE THREAD

**Issue by TheChilliPL** [Lattyware/massivedecks#185]
With automatic marking people as away disabled, time limits don't seem to work at all. The red bar on the top does get shown but doesn't move.
With automatic marking people as away enabled, I remember there was the issue that could mark some people as away right as the game starts, but I'm not sure if that's still an issue.

**Comment by Lattyware** [comment]
I think this should be fixed by the latest update, hopefully. I'll close this issue for now, but please reopen or make a new issue if you find it can still happen.
