### ISSUE TITLE
Website isn't loading.

### ISSUE THREAD

**Issue by kittyrose87** [Lattyware/massivedecks#190]
When opening the website, all I see is a textured blank screen. No load up of any items to start games/logo or anything.
Have tried different browsers and have refreshed several times. 
I am using windows 10 and have also tried to open on my iphone 11 but no response there either. 

Thanks.

**Comment by Lattyware** [comment]
Apologies for this, there was an issue upgrading to Webpack 5, I've rolled back for now and the new version is currently building, should be up soon.

**Comment by Lattyware** [comment]
OK, back up and working, sorry about that!
