### ISSUE TITLE
How should I change the text of Game Descriptions, House Rules etc. ? 

### ISSUE THREAD

**Issue by mukberty** [Lattyware/massivedecks#196]
I wish to change the names of house rules, their descriptions and other stuff defined in `massivedecks/client/src/elm/MassiveDecks/Strings/Languages/En/Internal.elm`.
Eg:
`New Game Description:` 
From--> `Start A New Game Of Massive Decks.` 
To -->`Start A New Game On John's CAH Server !!`

I understand that I can't directly go and change it in `Internal.elm` as it then causes errors while importing.
So will I have to make changes in the whole project to incorporate the new names, or is there any other way ?
Thanks 

P.S. Sorry for the enhancement label. I did a `Feature Request` by mistake.

**Comment by Lattyware** [comment]
> I understand that I can't directly go and change it in Internal.elm as it then causes errors while importing.

I'm not sure what you mean here, but just changing the values in the localisation files as you suggest is the way to do this. You need to correctly follow the grammar and format of the file, but to change any text in the application you shouldn't need to touch any other files.

**Comment by mukberty** [comment]
Here is what I did:

````
JohnC ->
            [ Text "JohnC" ]

        WhatIsThis ->
            [ Text "What is ", ref JohnC, Text "?" ]
        GameDescription ->
            [ ref JohnC
            , Text " is a comedy party game based on "
            , ref CardsAgainstHumanity
            , Text ", developed by "
            , ref RereadGames
            , Text " and other contributors—the game is open source under "
            , ref License
            , Text ", so you can help improve the game, access the source code, or just find out more at "
            , ref MDProject
            , Text "."
            ]
 NewGameDescription ->
            [ Text "Start a new game of ", ref JohnC, Text "." ]
````
The errors I got when I did `npm run dev`

````
ERROR in ./src/elm/MassiveDecks.elm
Module build failed (from ./node_modules/elm-webpack-loader/index.js):
Error: Compiler process exited with error Compilation failed
Compiling ...-- NAMING ERROR --------- src/elm/MassiveDecks/Strings/Languages/En/Internal.elm

I cannot find a `JohnC` variant:

13|         JohnC ->
            ^^^^^
These names seem close though:

    Blank
    Call
    Close
    Error

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

-- NAMING ERROR --------- src/elm/MassiveDecks/Strings/Languages/En/Internal.elm

I cannot find a `JohnC` variant:

75|             [ Text "Start a new game of ", ref JohnC, Text "." ]
                                                   ^^^^^
These names seem close though:

    Blank
    Call
    Close
    Error

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.


````
And so on  for every line I did this with.

**Comment by CookieCoder15** [comment]
The issue is that you have changed the `MassiveDecks` case to `JohnC`. The simplest way to do what you want based on the snippet of code you showed is this:

```
MassiveDecks ->
            [ Text "JohnC" ]

        WhatIsThis ->
            [ Text "What is ", ref MassiveDecks, Text "?" ]
        GameDescription ->
            [ ref MassiveDecks
            , Text " is a comedy party game based on "
            , ref CardsAgainstHumanity
            , Text ", developed by "
            , ref RereadGames
            , Text " and other contributors—the game is open source under "
            , ref License
            , Text ", so you can help improve the game, access the source code, or just find out more at "
            , ref MDProject
            , Text "."
            ]
 NewGameDescription ->
            [ Text "Start a new game of ", ref MassiveDecks, Text "." ]
```

**Comment by CookieCoder15** [comment]
Alternatively, you could leave your changes as they are and just replace `MassiveDecks` with `JohnC` in `client/src/elm/MassiveDecks/Strings.elm`.

**Comment by mukberty** [comment]
Thank You. It works now. I did the first solution.
