### ISSUE TITLE
How can I edit the CAH text on the cards that are displayed during a game ?

### ISSUE THREAD

**Issue by mukberty** [Lattyware/massivedecks#198]
I wish to change the CAH text displayed on cards to something else.
This isn't defined in `client/src/scss/_cards.scss`  or anywhere else, nor could I find anything in `client/assets/images` that might show a default black or white card (without any questions/responses on them).
Is the code dealing with this in this repo, or do you source them from an external source ?
Thank You .

**Comment by Lattyware** [comment]
What do you mean by "the CAH text"? If you mean the deck name bottom left, that's defined by [the name of the source](https://github.com/Lattyware/massivedecks/blob/master/server/src/ts/games/cards/source.ts#L26), which is implemented in different ways for each deck source. If you mean for built-in decks, it's just [in the deck file](https://github.com/Lattyware/massivedecks/blob/master/server/decks/cah-base-en.deck.json5#L4).

**Comment by mukberty** [comment]
Thank You.
That is what I meant.
