### ISSUE TITLE
Heroku Deployment Not working 

### ISSUE THREAD

**Issue by Yash-Git-Hub** [Lattyware/massivedecks#199]
The heroku deployment is no longer working due to some error in build logs posted below 

x: installed 1 in 1.406s
       error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
       error TS6046: Argument for '--module' option must be 'commonjs', 'amd', 'system' or 'umd'.
       error TS5023: Unknown compiler option 'incremental'.
       error TS5023: Unknown compiler option 'resolveJsonModule'.
       error TS5023: Unknown compiler option 'strict'.
       error TS5023: Unknown compiler option 'strictNullChecks'.
       error TS5023: Unknown compiler option 'strictFunctionTypes'.
       error TS5023: Unknown compiler option 'strictBindCallApply'.
       error TS5023: Unknown compiler option 'strictPropertyInitialization'.
       error TS5023: Unknown compiler option 'noImplicitThis'.
       error TS5023: Unknown compiler option 'alwaysStrict'.
       error TS5023: Unknown compiler option 'noImplicitReturns'.
       error TS5023: Unknown compiler option 'noFallthroughCasesInSwitch'.
       error TS5023: Unknown compiler option 'moduleResolution'.
       error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @massivedecks/server@2.0.0 build: `npx tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @massivedecks/server@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.2Yu0B/_logs/2020-10-22T08_59_15_483Z-debug.log
npm ERR! weird error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! massivedecks@2.0.0 buildServer: `npm explore @massivedecks/server -- npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the massivedecks@2.0.0 buildServer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.2Yu0B/_logs/2020-10-22T08_59_15_514Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! massivedecks@2.0.0 build: `cp -r server/decks decks && npm run buildServer && npm run buildClient`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the massivedecks@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.2Yu0B/_logs/2020-10-22T08_59_15_540Z-debug.log
-----> Build failed

**Comment by Lattyware** [comment]
Closed in favour of #176, already tracking this issue.
