### ISSUE TITLE
Skipping without anyone playing a card

### ISSUE THREAD

**Issue by kuriye** [Lattyware/massivedecks#201]
If you skip the round, if nobody played  a card you can't continue the game and it just stops there

**Comment by Lattyware** [comment]
Sounds like we aren't doing a check we should be for that. Thanks for the report, I'll try to get to it when I have a moment.

**Comment by lhvy** [comment]
Trying to work out what skipping a round means... Does this happen when all players (ignoring the card czar) are marked as away?
