### ISSUE TITLE
What about a (cross-platform) desktop client for MassiveDecks?

### ISSUE THREAD

**Issue by raphipod** [Lattyware/massivedecks#202]
What would you think about a desktop client for MD? Would it be unnecessary, or a great idea?

(I know it's not really an issue!)

**Comment by Lattyware** [comment]
Issues are the right way to give ideas and suggestions, so don't worry about that.

A desktop client is something we've thought about, if we were to do it, it shouldn't be too hard to do by just embedding the web app in Electron, but that wouldn't really offer much value as most people have browsers.

The main upside would be that it might allow us to do a Steam integration for things like inviting friends through Steam, which would be nice, but probably not worth the relative development effort for now. With that said, it might be something we look to do in the future.

Was there a particular idea you had about what you'd want the desktop client to do that the web client can't? If there was anything else that might push us to prioritise implementing such a thing sooner, but as far as I can think of, there isn't too much.

**Comment by raphipod** [comment]
Good point.

As I also got to do a lot with Electron, I thought of making a desktop app by **myself** (ofc with contributions from others), but as you said, it wouldn't be of much value.
