### ISSUE TITLE
Massive Decks Unexpected Error

### ISSUE THREAD

**Issue by rsadoff** [Lattyware/massivedecks#204]
I was trying to enter my game when I got the following error:

The server gave a response we didn’t expect.

Context for developers:
	Version: f5ce909269a152dfc4a4facfb702b1947494967f-dev
	Page: https://md.rereadgames.com/#M0DYO
	English Error: The server gave a response we didn’t expect.
	Details: 502

**Comment by Lattyware** [comment]
This appears to have been an issue with the docker environment on the hosted server, and should be fixed now. Please create a new issue if this happens again, and thanks for the report.
