### ISSUE TITLE
somthing went wrong

### ISSUE THREAD

**Issue by ZoruaBit** [Lattyware/massivedecks#205]
I was playing the game when I got the following error:

The server gave a response we didn’t understand.

Context for developers:
	Version: f5ce909269a152dfc4a4facfb702b1947494967f-dev
	Page: https://md.rereadgames.com/games/ZL0
	English Error: The server gave a response we didn’t understand.
	Details: Problem with the value at json.expected:

    [
        "Revealing",
        "Judging",
        "Complete"
    ]

Expecting a STRING

**Comment by Lattyware** [comment]
This seems to be a common issue from #206—I'll try to track down the root cause when I get the chance, but if anyone else wants to take a look and work out what the issue is here I'd welcome the help.

**Comment by Lattyware** [comment]
So looking at this, I believe the cause of this is liking a play too late, when the round is over. This can easily happen if you like a play just as the round finishes.

In general, this shouldn't cause any problems, just refresh to get rid of the error. I'll fix this properly by just ignoring it with my next changes.
