### ISSUE TITLE
Server crash?

### ISSUE THREAD

**Issue by Frenzy778** [Lattyware/massivedecks#206]
I was playing, when the TTS went silent, I continued playing for 2 more rounds when I got the following error:

The server gave a response we didn’t understand.

Context for developers:
	Version: f5ce909269a152dfc4a4facfb702b1947494967f-dev
	Page: https://md.rereadgames.com/games/QXX3
	English Error: The server gave a response we didn’t understand.
	Details: Problem with the value at json.expected:

    [
        "Revealing",
        "Judging",
        "Complete"
    ]

Expecting a STRING

**Comment by Lattyware** [comment]
Hrm, looks like the same bug as #205. I'll close this issue and track the bug in that issue, thanks for the extra report though, it's useful when trying to track down bugs like this.
