### ISSUE TITLE
Heroku deploy doesn't work

### ISSUE THREAD

**Issue by Piteus** [Lattyware/massivedecks#209]
## Describe the bug
Heroku button to deploy doesn't work, build failed with this error:

> -----> nginx-buildpack app detected
./
./nginx
./mime.types
./nginx-debug
-----> nginx-buildpack: Installed nginx/1.18.0 to app/bin
-----> nginx-buildpack: Added start-nginx to app/bin
-----> nginx-buildpack: Added start-nginx-debug to app/bin
-----> nginx-buildpack: Added start-nginx-solo to app/bin
-----> nginx-buildpack: Default mime.types copied to app/config/
-----> nginx-buildpack: Custom config found in app/config.
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  14.x.x
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 14.x.x...
       Downloading and installing node 14.15.3...
       Using default npm version: 6.14.9
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       > @fortawesome/fontawesome-free@5.15.1 postinstall /tmp/build_137cc1d3_/node_modules/@fortawesome/fontawesome-free
       > node attribution.js
       
       Font Awesome Free 5.15.1 by @fontawesome - https://fontawesome.com
       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
       
       added 338 packages from 187 contributors and audited 338 packages in 18.961s
       
       4 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
-----> Build
       Running build
       
       > massivedecks@2.0.0 build /tmp/build_137cc1d3_
       > cp -r server/decks decks && npm run buildServer && npm run buildClient
       
       
       > massivedecks@2.0.0 buildServer /tmp/build_137cc1d3_
       > npm explore @massivedecks/server -- npm run build
       
       
       > @massivedecks/server@2.0.0 build /tmp/build_137cc1d3_/server
       > npx tsc
       
npx: installed 1 in 1.429s
       error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
       error TS6046: Argument for '--module' option must be 'commonjs', 'amd', 'system' or 'umd'.
       error TS5023: Unknown compiler option 'incremental'.
       error TS5023: Unknown compiler option 'resolveJsonModule'.
       error TS5023: Unknown compiler option 'strict'.
       error TS5023: Unknown compiler option 'strictNullChecks'.
       error TS5023: Unknown compiler option 'strictFunctionTypes'.
       error TS5023: Unknown compiler option 'strictBindCallApply'.
       error TS5023: Unknown compiler option 'strictPropertyInitialization'.
       error TS5023: Unknown compiler option 'noImplicitThis'.
       error TS5023: Unknown compiler option 'alwaysStrict'.
       error TS5023: Unknown compiler option 'noImplicitReturns'.
       error TS5023: Unknown compiler option 'noFallthroughCasesInSwitch'.
       error TS5023: Unknown compiler option 'moduleResolution'.
       error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @massivedecks/server@2.0.0 build: `npx tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @massivedecks/server@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.4t2L1/_logs/2020-12-19T18_00_35_341Z-debug.log
npm ERR! weird error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! massivedecks@2.0.0 buildServer: `npm explore @massivedecks/server -- npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the massivedecks@2.0.0 buildServer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.4t2L1/_logs/2020-12-19T18_00_35_369Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! massivedecks@2.0.0 build: `cp -r server/decks decks && npm run buildServer && npm run buildClient`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the massivedecks@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.4t2L1/_logs/2020-12-19T18_00_35_394Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by Lattyware** [comment]
Yes, unfortunately this is a known issue, I'll close this as a duplicate and if you want to follow this issue you can see the updates in #176.
