### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by Piteus** [Lattyware/massivedecks#210]
Stavo aprendo quando è apparso il seguente errore:

Il server ha dato una risposta inaspettata.

Context for developers:
	Version: f5ce909269a152dfc4a4facfb702b1947494967f-dev
	Page: https://md.rereadgames.com/#new
	English Error: The server gave a response we didn’t expect.
	Details: 522

**Comment by Lattyware** [comment]
Thanks for the report, looking into it now.

**Comment by Lattyware** [comment]
This should be fixed now,

The issue was a hard crash on the instance for some reason and our cloud provider had issues restarting the instance. It's been rebuilt and should be up and running again.
