### ISSUE TITLE
The 'Card Czar Choices' function is not working correctly. 

### ISSUE THREAD

**Issue by rickklopping** [Lattyware/massivedecks#213]
![Screenshot 2021-01-02 132113](https://user-images.githubusercontent.com/43129716/103457217-6c291280-4cfd-11eb-9830-4ed3af8e3d61.jpg)
## Describe the bug
When a game is played with 'Card Czar Choices' off, it appears that this function is somehow active. The first round runs flawlessly, but there seems something wrong at the start of the second round. Here, you have to wait at least 30 seconds. When you click on the '?' button, it says 'You are waiting for the Card Czar to pick a Black Card for you to play into'. This should not be possible, as this option is turned off in the settings. 

## How to reproduce the bug
Steps to reproduce the behaviour:
1. Start a new game
2. Disable 'Card Czar Choices'
3. Let others join and start the game
4. Play the first round
5. Choose the winning combination
6. Go to the next round

### Expected behaviour
At the start of the second round, the black card does not become visible and the white cards remain grey for at least 30 seconds. When you click on the '?' button, it says 'You are waiting for the Card Czar to pick a Black Card for you to play into'. This should not be possible, as this option is turned off in the settings.

**Comment by Lattyware** [comment]
Yeah, that sounds like a bug. For now, it sounds like it is running the stage in the background, very weird, but if you set the time limit down to 1 it should minimise the impact.

I'll try to get a fix in ASAP.

**Comment by Lattyware** [comment]
OK, resolved. I'll push the fix to the hosted version once the build goes through. Thanks for the report.
