### ISSUE TITLE
Error loading deck from Many Decks

### ISSUE THREAD

**Issue by Scarlet06** [Lattyware/massivedecks#214]
When I try to upload any deck from Many Decks (https://decks.rereadgames.com/) it just start loading but never end. 

![image](https://user-images.githubusercontent.com/50097169/103698369-8c78fb80-4fa1-11eb-913c-0a92a5cf3c80.png)

Selecting the loading deck, it shows that it doesn't exist.

![image](https://user-images.githubusercontent.com/50097169/103698511-bd593080-4fa1-11eb-904b-2ade7453ebd1.png)

I've noticed that the problem is in the link of the given deck which is something like "https://decks.rereadgames.com//decks/1GXEP" with 2 "/" instead of "https://decks.rereadgames.com/decks/1GXEP".

**Comment by Lattyware** [comment]
OK, I've fixed this in the live environment, it's just a configuration error with an extra trailing slash on the URL in the config file.

I'll leave this issue open for now as the default value should be changed and we should trim trailing slashes from the URL so this mistake doesn't matter if it happens.

**Comment by faraoman** [comment]
this issue is still present

**Comment by Lattyware** [comment]
I'm not sure what caused this to regress, but I've redeployed and things appear to be working again.

**Comment by FlareBeast** [comment]
The url issue seems to be back for me and a few friends trying to use our custom deck... attempting to use other custom decks results in the same issue

**Comment by Lattyware** [comment]
Hrm, this must be an issue with the deployment. My assumption is that somehow the container is ending up without the production configuration mounted, but I have no idea how/why that is happening. Obviously not ideal. I'll take a closer look when I get the chance.

**Comment by Lattyware** [comment]
I think this should be permanently resolved now. Please open a new issue if you run into it again.
