### ISSUE TITLE
.

### ISSUE THREAD

**Issue by iamnottasty-afk** [Lattyware/massivedecks#216]
The server gave a response we didn’t expect.

Context for developers:
	Version: 6b18d67459244f13d7dd875f94db39f38a706741-dev
	Page: https://md.rereadgames.com/#new
	English Error: The server gave a response we didn’t expect.
	Details: 522

**Comment by Lattyware** [comment]
I believe that this was just the server being down, and should be fixed now. Apologies for that, if you continue to have problems, please create a new issue for it.
