### ISSUE TITLE
Loading Errors

### ISSUE THREAD

**Issue by hughesation** [Lattyware/massivedecks#217]
I was loading the page when I got the following error:

The server gave a response we didn’t expect.

Context for developers:
	Version: 6b18d67459244f13d7dd875f94db39f38a706741-dev
	Page: https://md.rereadgames.com/#new
	English Error: The server gave a response we didn’t expect.
	Details: 502

**Comment by Lattyware** [comment]
Looks like the server is having some load issues, I'll give it a kick and hopefully that should fix things.

**Comment by Lattyware** [comment]
OK, things seem to be running smoothly again. Please open a new issue if something goes wrong again.
