### ISSUE TITLE
We have been playing 8 people and the server crash out

### ISSUE THREAD

**Issue by RodriguezRuizI** [Lattyware/massivedecks#219]
I was [replace with a short explanation of what you were doing] when I got the following error:

The server gave a response we didn’t expect.

Context for developers:
	Version: 6b18d67459244f13d7dd875f94db39f38a706741-dev
	Page: https://md.rereadgames.com/#new
	English Error: The server gave a response we didn’t expect.
	Details: 522

**Comment by Lattyware** [comment]
Sorry, the server seems to have been automatically rebooted to apply an important security patch. Just bad luck timing-wise.
