### ISSUE TITLE
Massive decks down

### ISSUE THREAD

**Issue by Quackerz97** [Lattyware/massivedecks#226]
I hopped onto the site when I got the following error:

The server gave a response we didn’t expect.

Context for developers:
	Version: 6b18d67459244f13d7dd875f94db39f38a706741-dev
	Page: https://md.rereadgames.com/#new
	English Error: The server gave a response we didn’t expect.
	Details: 502

**Comment by Lattyware** [comment]
Fixed, sorry for that.
