### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Ccindyy** [Lattyware/massivedecks#240]
![error](https://user-images.githubusercontent.com/77591024/129303142-209082f9-6bd6-4c70-8b71-8a2b7ea92cd3.JPG)

I got an error when there wasn't enough in the deck, but there was no way to dismiss the error message. It prevented us from continuing the game and choosing the cards (since the button to choose is also at the bottom of the screen so it's been covered up) or get rid of the pop up notifications from discards. The error was still there after I reloaded the page.

**Comment by Lattyware** [comment]
Unfortunately this does totally break the game. We don't have a good system for adding cards in to resolve this during the game at the moment, and playing on without enough cards would cause further issues for sure.

I agree this is a poor behaviour, and something it'd be nice to fix, it's actually already tracked as an open issue at #104 so I'll close this as a duplicate, and you can follow that issue for updates on this problem.
