### ISSUE TITLE
arm64 builds for docker

### ISSUE THREAD

**Issue by KingPin** [Lattyware/massivedecks#241]
## Describe the feature
Hi I noticed you are using GitHub actions to build the docker image and pushing it to docker, ghcr.io, if you switch to buildx you can have it compile the image on arm7/8 & amd64 in one go and push to both docker hub and ghcr.io.  an example page describing the flow: https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

thank you.

**Comment by Lattyware** [comment]
I've actually looked at this, it's a good idea and something I want to do, just not had the time to sort it.

Definitely on my radar though, and planned.

**Comment by KingPin** [comment]
awesome, here's my foray into this venture, if you use something like this you just need to change the package name at the bottom and add dockerhub user and pass to your repo secrets, this will work out of the box for arm64 and amd64 : https://github.com/KingPin/ripe-atlas-docker/blob/master/.github/workflows/docker-image.yml

all it requires is a Dockerfile in the repo. this will push to both ghcr and dockerhub.

**Comment by Lattyware** [comment]
As of the latest build there are now arm64 images in the repositories.
