### ISSUE TITLE
When 2 players simultaneously start a new game from the same lobby the resulting game state shows 2 players as czar.

### ISSUE THREAD

**Issue by mpforce1** [Lattyware/massivedecks#33]

**Comment by mpforce1** [comment]
The following error occurs when attempting to start the game twice as per this bug:

Got an action (StartGame (Result { lobby = { id = "yx", config = { decks = [{ id = "B80VA", name = "Massive Decks", calls = 279, responses = 773 }] }, players = [{ id = 0, name = "t1", status = Czar, score = 0 },{ id = 1, name = "t2", status = Czar, score = 0 }], round = Just { czar = 1, call = ["Every time I talk about it, I have you seriously play down my obsession with ","."], responses = Hidden 0 } }, hand = { hand = ["feeding a cash machine a stray cat","having a dick the shape of which can only be described by a mathematical formula 7 pages long","goth clunge","spirituality","the sound of nails on a chalkboard","finding things in my vagina","2 minutes in heaven"] } })) that can't be handled in the current state (Playing).

Then the client then switches to the winning card state as if it had just played out a round.

When pressing the next round button and starting a new round the user selecting will be unable to submit a card, receiving a 400 Bad Request response.

**Comment by Lattyware** [comment]
d9df15a6c297cdc5407c74f6a4bbbc5a1d333a9a may have resolved this, testing required.

**Comment by Lattyware** [comment]
Pretty sure this is resolved, not seen since. If you do see it, raise a new issue.
