### ISSUE TITLE
House Rule: Happy Ending

### ISSUE THREAD

**Issue by Lattyware** [Lattyware/massivedecks#49]
Add a new house rule that can be enabled from the house rules during game setup:

> When the game ends, the final round is a 'Make a Haiku' black card.

This task is marked as a good first issue. If you would like to contribute but are unsure where to start, please take a look at [the wiki for how to set up a development environment](https://github.com/Lattyware/massivedecks/wiki/Setting-Up-A-Development-Environment), and feel free to ask if you are still not sure.

**Comment by CookieCoder15** [comment]
I am currently working on this. So far I have managed to make a rule trigger an extra round once someone wins and also added the Happy Ending rule to both client and server. I am having two issues I would appreciate help with:

- How do I force a certain card when starting a new round? My attempts so far have been unsuccessful.
- When I enable my new rule and press save, I get this error `The server didn't understand a request from the client. Details: Error: Invalid PublicConfig: PublicConfig.rules.houseRules should NOT have additional properties` I think the issue is due to my manual editing of _validation.validator.ts_ as I can see it was generated by _typescript-json-validator_, but I'm unsure how to regenerate/edit this file correctly.

**Comment by Lattyware** [comment]
Great to hear you are working on it.

Forcing a card would involve changing the way the round is generated. We do this in [`game.startNewRound()`](https://github.com/Lattyware/massivedecks/blob/master/server/src/ts/games/game.ts#L231), and more specifically [we replace the old call with a new one](https://github.com/Lattyware/massivedecks/blob/master/server/src/ts/games/game.ts#L251). Instead, you would want to discard the old one, but then inject the specific call you want as the new one instead of drawing one off the deck.

You should be able to generate `validation.validator.ts` with `npm run generate-json-validators`, which should hopefully then fix that issue.

**Comment by CookieCoder15** [comment]
I have everything sorted now except for sending a specific card. I think I know the correct spot to do so and have added comments there but I don't know how to choose a specific call or choose one from a deck that isn't enabled in the case the selected decks don't include the base deck.

**Comment by Lattyware** [comment]
There are a couple of ways to go about that, in theory you could go for something very complex where the user can select a call or something, but I'd recommend against that (or if you think it is valuable, make a new issue and do it more simply first).

What I'd suggest is just hard-coding a call as a constant, which in the case of the house rule as described is fine. The difficult part of this is the source, I would suggest making a new source like `Custom` called `Generated`.

Then it's just a case of making the card with that source, i.e:

```
const happyEndingCall: Call = {
  id: Card.id(),
  parts: [
    ["Make a haiku."],
    [
      {
        transform: "Capitalize",
      },
      ",",
    ],
    [
      {
        transform: "Capitalize",
      },
      ",",
    ],
    [
      {
        transform: "Capitalize",
      },
      ".",
    ],
  ],
  source: { source: "Generated" },
};
```

Obviously, this falls over when it comes to localization, but that is harder to solve as we don't have translations of the base deck for all languages. I would suggest that is a problem for another issue.

**Comment by CookieCoder15** [comment]
For now, I think I will hard-code the card in. I have managed to get everything working so expect a pull request soon!

**Comment by Lattyware** [comment]
In as of #179 being merged, thanks to @CookieCoder15! :tada:
