### ISSUE TITLE
Project deprecated?

### ISSUE THREAD

**Issue by mwllgr** [Lattyware/massivedecks#546]
Hi, since there haven't been any commits since June of last year, is this project deprecated?
If so, please add a disclaimer to the README.

**Comment by Lattyware** [comment]
It isn't, I've just been busy and haven't had a chance to update some time. I have most of a large update ready, but need to find the time to do a full release.

**Comment by mwllgr** [comment]
So nice to hear that - thanks for your fast response! Would love to see the "unfinished" update in a separate branch, this way people could contribute.
