### ISSUE TITLE
Server Error when loading Find or Join tabs

### ISSUE THREAD

**Issue by tedbroda** [Lattyware/massivedecks#553]
I was loading the "Find" tab when I got the following error:

This same error happened reproducibly for the "join" tab and in different browsers. I am using an Android mobile device. 

The server gave a response we didn’t expect.

Context for developers:
	Version: v2.8.0
	Page: https://md.rereadgames.com/#find
	English Error: The server gave a response we didn’t expect.
	Details: 502

**Comment by Lattyware** [comment]
Not sure what happened here, but seems to be working again after a restart. Please open a new issue if the issue reappears, but I think this is solved for now.
