### ISSUE TITLE
Add support for blank white cards.

### ISSUE THREAD

**Issue by Lattyware** [Lattyware/massivedecks#58]
Add the ability to add a number of blank white cards to the deck, which can be filled in when they are played.

**Comment by CookieCoder15** [comment]
Any progress with this enhancement? I don't know elm but would love to see this feature implemented as it is the one thing I can't find that is in similar games.

**Comment by Lattyware** [comment]
This had actually been sat half-implemented for a long time. I've mostly fixed it up—there is still something a big buggy with the text input on the cards at the moment (you might have to click a few times)—I'll look into that and create an issue for it, but it fundamentally appears to work.
