### ISSUE TITLE
Adding a button that fetches a deck

### ISSUE THREAD

**Issue by AnonEstranho** [Lattyware/massivedecks#67]
Hey. New elm user here, starting to learn it. I am using massivedecks to make an online portuguese cards against humanity clone, and I am having difficulty adding a button that fetches a deck already made.

Any insight or help you can provide?

**Comment by Lattyware** [comment]
If you mean adding a CardCast deck, then there is a mechanism for doing so already in the game, which is to make the button trigger a `ConfigureDecks (Request "DECKCODE")`.

e.g: In [Config/UI.elm](https://github.com/Lattyware/massivedecks/blob/master/client/src/MassiveDecks/Scenes/Config/UI.elm):
```
a [ class "link"
            , attribute "tabindex" "0"
            , attribute "role" "button"
            , onClick (ConfigureDecks (Request "CAHBS"))
            ] [ text "clicking here to add the Cards Against Humanity base set" ]
```

If you want to create a new source for the deck other than CardCast, you would need to add support for such a thing. You'd want to begin with implementing something like [CardcastAPI](https://github.com/Lattyware/massivedecks/blob/master/app/massivedecks/cardcast/CardcastAPI.scala) that provides decks drawing from your source, and then wire that into the configuration UI.

**Comment by AnonEstranho** [comment]
Hey sorry to bother you again, but which program do you recommend to edit this project .css file? I am trying to live preview it, but finding it difficult to do.

**Comment by Lattyware** [comment]
See https://github.com/Lattyware/massivedecks/wiki/Setting-Up-A-Development-Environment for my suggestions on editors, etc...

**Comment by AnonEstranho** [comment]
I noticed that, but how did you code the webpage? I can't find any .html file, and the .css file has loads of stuff. Should I just edit manually .css?

**Comment by Lattyware** [comment]
The site is an Elm web application with a server written in Scala - the CSS is compiled from LESS. You may want to take a look at the structure of the application and try to follow through how it works before attempting to start making changes. I'd suggest reading up on the languages used first and maybe playing with some new sample projects in each language to get a feel first.
