### ISSUE TITLE
Ability to translate cards

### ISSUE THREAD

**Issue by moutonnoireu** [Lattyware/massivedecks#69]
Hello ! I would love to host massivedecks in my language and have the ability to translate it. Could it be possible ?

**Comment by Lattyware** [comment]
Hi, you are abosultely able to host Massive Decks. Translation is something that's not currently set up, but could be added to the codebase.

If you are just interested in translating the cards themselves, you can just make (or find) the appropriate decks on [cardcast](https://www.cardcastgame.com/browse). You can then load and use those decks in Massive Decks. No coding required.

If you want to translate the interface, that is unfortuntately not currently something with a process around it. If you wanted to write in the changes to allow for internationalisation, I would accept a merge request, but that would require a fair amount of coding.

**Comment by moutonnoireu** [comment]
I'm in no way a coder and I will try to translate the official deck, thanks for the idea. :)
