### ISSUE TITLE
"Deploy to Heroku" button does not function

### ISSUE THREAD

**Issue by Avamander** [Lattyware/massivedecks#71]
After pressing the button, not changing anything in the configuration and then starting MD, for some reason MD can not be accessed, the port provided in the heroku log does not allow establishing connection.

**Comment by Lattyware** [comment]
You will need to change the hostname to the correct hostname for your deployment (by default 'yourappname.herokuapp.com' replacing 'yourappname' with the value you choose for heroku.

The port in the logs is internal and provided by heroku. You should be able to access it on port 80 like any normal site.

**Comment by Avamander** [comment]
Okay, thanks, that seems to have fixed it. Though a small paragraph about it in the Wiki wouldn't hurt.

**Comment by Lattyware** [comment]
I've added [a deployment page](https://github.com/Lattyware/massivedecks/wiki/Deploying) to explain the process.

**Comment by Avamander** [comment]
Really nice!
