### ISSUE TITLE
Other language translation - add an option to select languages

### ISSUE THREAD

**Issue by Tekameikite** [Lattyware/massivedecks#73]
Hey! Are you interested in Polish translation for your app? Many of my friends use this app and they would be happy to see it in our language! I could translate it if you want.

**Comment by Lattyware** [comment]
Hi, thanks for the comment. Translation is definitely something I'd love to do, but currently the app simply isn't set up for localisation.

I am planning a new version with significant changes, probably after the next version of Elm comes out. Part of that will include adding localisation support so translators like yourself can easily add translations.

When that support is in place, translation should become a simple task and I'll happily accept a merge request with a translation if you can supply it. That'd be great. I'll ping this issue when that is in, and if you are still willing and able, it should be a simple thing.

**Comment by Lattyware** [comment]
Implemented in 2.x.
