### ISSUE TITLE
CardCast 

### ISSUE THREAD

**Issue by ronanwyatt** [Lattyware/massivedecks#74]
I was trying to start a game when a cardcast error occured and will not load.Application Info:Version: 9b74f7e-devURL: https://massivedecks.herokuapp.com/

**Comment by Lattyware** [comment]
Checking now, I can't reproduce - I suspect that this was just that Cardcast's API was temporarily down, which is outside of our control. Please try again and let me know if this is still an issue for you.

**Comment by ronanwyatt** [comment]
Thank you! The Card Cast was just emporaily down
________________________________
