### ISSUE TITLE
Round doesn't proceed to Selection when player leaves

### ISSUE THREAD

**Issue by spankety** [Lattyware/massivedecks#81]
A player left the game after apparently playing a card. I got an <!> alert indicating the player had left and another <!> alert indicating the player was inactive. It offered to let me skip them, but when i clicked Skip i got an error saying i couldn't skip them because they weren't inactive. Then the screen never timed out and proceeded to selection so we had to restart the game. .Application Info:Version: 9b74f7e-devURL: https://massivedecks.herokuapp.com/

**Comment by Lattyware** [comment]
Sounds like a bug for sure. Probably a server state issue - this should hopefully be fixed by the new state management in the next version.

**Comment by Lattyware** [comment]
With the server rewrite for 2.x, this bug should no longer exist.
