### ISSUE TITLE
Missing Sources?

### ISSUE THREAD

**Issue by Xipherisroot** [Lattyware/massivedecks#83]
Output when attempting to launch on Heroku

> -----> Source app detected
-----> Creating profile.d script
       SOURCE_VERSION: 
       Script installed to .profile.d/source_version.sh
-----> Elm app detected
-----> Retrieving 0.18.0
https://s3.amazonaws.com/heroku-buildpack-elm/assets/elm/0.18.0/elm:
2019-01-29 06:03:58 ERROR 403: Forbidden.
 !     Push rejected, failed to compile Elm app.
 !     Push failed

**Comment by Lattyware** [comment]
This is, unfortunately, a known issue upstream with heroku-buildpack-elm. See #79 for details on work-arounds. A proper fix will come with the next version of Massive Decks, which is blocked on WebSocket support in the newest version of Elm.

**Comment by Lattyware** [comment]
This is essentially resolved with 2.x.
