### ISSUE TITLE
Menus don't work on specific devices.

### ISSUE THREAD

**Issue by Lattyware** [Lattyware/massivedecks#90]
Might be an issue with touch events vs click events?

**Comment by ryuheiyokokawa** [comment]
Bump on this one.  Confirmed for both iPad and iPhone devices (latest Chrome as of April 2020).

**Comment by Lattyware** [comment]
Pretty sure this is fundamentally an issue in Weightless, so the reality is this probably gets fixed with #117, which is unfortunately a reasonably large task.

**Comment by ryuheiyokokawa** [comment]
@Lattyware Gotcha.  Thanks for letting me know.  I'll just make sure they're on desktop!  This is really awesome for the quarantine times.

**Comment by Lattyware** [comment]
Since #117, I'm hoping this is now resolved. If anyone can try with a device that had issues before and can say either way, I'd love to know.

**Comment by Lattyware** [comment]
Given the lack of feedback here, I'm going to assume this is now working as intended and close this issues. If anyone *does* run into this or a similar issue, please re-open or open a new bug.
