### ISSUE TITLE
Can't add decks

### ISSUE THREAD

**Issue by harumhl** [Lattyware/massivedecks#91]
I was trying to add a new deck (and the error can also happen to the base deck), but I received 502 Bad Gateway error quite often.

POST https://massivedecks.herokuapp.com/api/lobbies/XV 502 (Bad Gateway)

Application Info:Version: 9b74f7e-devURL: https://massivedecks.herokuapp.com/

**Comment by Lattyware** [comment]
Sorry for the slow response—this is most likely just that CardCast was down or refusing our connections. If you continue to get this issue longer-term, then do comment again, but I think it is likely this was just a short-term issue.
