### ISSUE TITLE
Deck doesnt work

### ISSUE THREAD

**Issue by zaad4u** [Lattyware/massivedecks#93]
I wanted to play a game, but i couldnt select a deck. Can this be fixed ASAP?Application Info:Version: Not SpecifiedURL: https://scoutsagainsthumanity.herokuapp.com/

**Comment by Lattyware** [comment]
Sorry, this instance of the game isn't managed by me, and has been modified, so I can't really offer any help on it. I would suggest going to the maintainer.

That said, I imagine this was just CardCast being down—an intermittent fault that only they could fix.
